ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: vehicle_events_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: vehicle-events-api