output = "internal/db/models"
no-tests = true

[psql]
dbname = "vehicle_events_api"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = ""
schema = "public"
sslmode= "disable"
blacklist = ["goose_db_version"]
