replicaCount: 1
image:
  repository: dimozone/vehicle-events-api
  pullPolicy: IfNotPresent
  tag: '6842576'
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
env:
  ENVIRONMENT: dev
  PORT: '8080'
  MONITORING_PORT: '8888'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: vehicle_events_api
  DB_SSL_MODE: require
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  SERVICE_NAME: vehicle-events-api
  JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://vehicle-events-api.dev.dimo.zone
  IDENTITY_API_URL: https://identity-api.dev.dimo.zone/query
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  DEVICE_SIGNALS_TOPIC: topic.device.signals
  TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://dex-roles-rights.dev.svc.cluster.local:5556/keys
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '3'
    external-dns.alpha.kubernetes.io/hostname: vehicle-events-api.dev.dimo.zone
  hosts:
    - host: vehicle-events-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
serviceMonitor:
  enabled: false
  path: /metrics
  port: mon-http
  interval: 30s
