definitions:
  controllers.SubscriptionView:
    properties:
      created_at:
        type: string
      description:
        type: string
      event_id:
        type: string
      vehicle_token_id:
        type: string
    type: object
info:
  contact: {}
  title: Vehicle Triggers API
  version: "1.0"
paths:
  /v1/webhooks:
    get:
      description: Retrieves all registered webhooks for the developer.
      produces:
      - application/json
      responses:
        "200":
          description: List of webhooks
          schema:
            items:
              type: object
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: List all webhooks
      tags:
      - Webhooks
    post:
      consumes:
      - application/json
      description: Registers a new webhook with the specified configuration. The target
        URI is validated to ensure it is a valid URL, responds with 200 within a timeout,
        and returns a verification token.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Webhook registered successfully
        "400":
          description: Invalid request payload or target URI
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Register a new webhook
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}:
    delete:
      description: Deletes a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Webhook deleted successfully
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Delete a webhook
      tags:
      - Webhooks
    get:
      description: Returns every vehicleTokenId currently subscribed.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all vehicles subscribed to a webhook
      tags:
      - Webhooks
    put:
      consumes:
      - application/json
      description: Updates the configuration of a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Webhook updated successfully
        "400":
          description: Invalid request payload
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Update a webhook
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/subscribe/{vehicleTokenId}:
    post:
      consumes:
      - application/json
      description: Associates a vehicle with a specific event webhook.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Vehicle assigned
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Assign a vehicle to a webhook
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/subscribe/all:
    post:
      description: Subscribes every vehicle shared with this developer to the webhook.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Count of subscribed vehicles
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Subscribe all shared vehicles
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/subscribe/csv:
    post:
      consumes:
      - text/csv
      description: Parses a CSV file from the request body and subscribes each vehicleTokenId
        to the webhook.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Count of subscribed vehicles
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Assign multiple vehicles to a webhook from CSV
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/unsubscribe/{vehicleTokenId}:
    delete:
      description: Removes a vehicle’s subscription.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle removed
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Unsubscribe a vehicle from a webhook
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/unsubscribe/all:
    delete:
      description: Removes every shared vehicle subscription for this webhook.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Count of unsubscribed vehicles
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Unsubscribe all shared vehicles
      tags:
      - Webhooks
  /v1/webhooks/{webhookId}/unsubscribe/csv:
    delete:
      consumes:
      - text/csv
      description: Parses a CSV file from the request body and unsubscribes each vehicleTokenId
        from the webhook.
      parameters:
      - description: Webhook ID
        in: path
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Count of unsubscribed vehicles
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Unsubscribe multiple vehicles from a webhook using CSV
      tags:
      - Webhooks
  /v1/webhooks/signals:
    get:
      description: Fetches the list of signal names available for the data field.
      produces:
      - application/json
      responses:
        "200":
          description: List of signal names
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Get signal names
      tags:
      - Webhooks
  /v1/webhooks/vehicles/{vehicleTokenId}:
    get:
      description: Retrieves all webhook subscriptions for a given vehicle.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.SubscriptionView'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List subscriptions for a vehicle
      tags:
      - Webhooks
securityDefinitions:
  BearerAuth:
    description: 'JWT Authorization header using the Bearer scheme. Example: "Bearer
      {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
