info:
  contact: {}
paths:
  /subscriptions/{eventID}:
    post:
      consumes:
      - application/json
      description: Takes a JSON array of vehicleTokenIDs in the request body and subscribes
        each to the event.
      parameters:
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      - description: List of Vehicle Token IDs
        in: body
        name: vehicleTokenIDs
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Summary message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload or missing IDs
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Subscribe multiple vehicles to a webhook
      tags:
      - Vehicle Subscriptions
  /subscriptions/{vehicleTokenID}:
    get:
      description: Retrieves all webhook subscriptions for a given vehicle.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of subscriptions
          schema:
            items:
              type: object
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: List subscriptions for a vehicle
      tags:
      - Vehicle Subscriptions
  /subscriptions/{vehicleTokenID}/event/{eventID}:
    delete:
      description: Unlinks a vehicle from a specific event webhook.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenID
        required: true
        type: string
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle removed from webhook successfully
        "400":
          description: Invalid vehicle token ID
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Remove a vehicle from a webhook
      tags:
      - Vehicle Subscriptions
    post:
      consumes:
      - application/json
      description: Associates a vehicle with a specific event webhook, optionally
        using conditions.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenID
        required: true
        type: string
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Vehicle assigned to webhook successfully
        "400":
          description: Invalid request payload or vehicle token ID
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Assign a vehicle to a webhook
      tags:
      - Vehicle Subscriptions
  /subscriptions/all/event/{eventID}:
    post:
      consumes:
      - application/json
      description: Subscribes every vehicle that has been shared with the authenticated
        developer license to the specified webhook event.
      parameters:
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully subscribed count
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request (e.g. missing eventID)
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized (invalid or missing JWT)
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Subscribe all shared vehicles to a webhook
      tags:
      - Vehicle Subscriptions
  /webhooks:
    get:
      description: Retrieves all registered webhooks for the developer.
      produces:
      - application/json
      responses:
        "200":
          description: List of webhooks
          schema:
            items:
              type: object
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: List all webhooks
      tags:
      - Webhooks
    post:
      consumes:
      - application/json
      description: Registers a new webhook with the specified configuration. The target
        URI is validated to ensure it is a valid URL, responds with 200 within a timeout,
        and returns a verification token.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Webhook registered successfully
        "400":
          description: Invalid request payload or target URI
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Register a new webhook
      tags:
      - Webhooks
  /webhooks/{id}:
    delete:
      description: Deletes a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Webhook deleted successfully
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Delete a webhook
      tags:
      - Webhooks
    put:
      consumes:
      - application/json
      description: Updates the configuration of a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Webhook updated successfully
        "400":
          description: Invalid request payload
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Update a webhook
      tags:
      - Webhooks
  /webhooks/signals:
    get:
      description: Fetches the list of signal names available for the data field.
      produces:
      - application/json
      responses:
        "200":
          description: List of signal names
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
      summary: Get signal names
      tags:
      - Webhooks
swagger: "2.0"
