info:
  contact: {}
paths:
  /subscriptions/{vehicleTokenID}/event/{eventID}:
    delete:
      description: Unlinks a vehicle from a specific event webhook.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenID
        required: true
        type: string
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle removed from webhook successfully
        "400":
          description: Invalid vehicle token ID
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Remove a vehicle from a webhook
      tags:
      - Vehicle Subscriptions
    post:
      consumes:
      - application/json
      description: Associates a vehicle with a specific event webhook, optionally
        using conditions.
      parameters:
      - description: Vehicle Token ID
        in: path
        name: vehicleTokenID
        required: true
        type: string
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Vehicle assigned to webhook successfully
        "400":
          description: Invalid request payload or vehicle token ID
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Assign a vehicle to a webhook
      tags:
      - Vehicle Subscriptions
  /webhooks:
    get:
      description: Retrieves all registered webhooks for the developer.
      produces:
      - application/json
      responses:
        "200":
          description: List of webhooks
          schema:
            items:
              type: object
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: List all webhooks
      tags:
      - Webhooks
    post:
      consumes:
      - application/json
      description: Registers a new webhook with the specified configuration.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Webhook registered successfully
        "400":
          description: Invalid request payload
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Register a new webhook
      tags:
      - Webhooks
  /webhooks/{id}:
    delete:
      description: Deletes a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Webhook deleted successfully
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Delete a webhook
      tags:
      - Webhooks
    put:
      consumes:
      - application/json
      description: Updates the configuration of a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Webhook updated successfully
        "400":
          description: Invalid request payload
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Update a webhook
      tags:
      - Webhooks
  /webhooks/signals:
    get:
      description: Fetches the list of signal names available for the data field.
      produces:
      - application/json
      responses:
        "200":
          description: List of signal names
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
      summary: Get signal names
      tags:
      - Webhooks
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
