basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Support Team
    url: http://www.swagger.io/support
  description: API for managing vehicle events and webhooks.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Vehicle Events API
  version: "1.0"
paths:
  /webhooks:
    get:
      description: Retrieves all registered webhooks for the developer.
      produces:
      - application/json
      responses:
        "200":
          description: List of webhooks
          schema:
            items:
              type: object
            type: array
        "500":
          description: Internal server error
      summary: List all webhooks
      tags:
      - Webhooks
    post:
      consumes:
      - application/json
      description: Registers a new webhook with the specified configuration.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Webhook registered successfully
        "400":
          description: Invalid request payload
        "500":
          description: Internal server error
      summary: Register a new webhook
      tags:
      - Webhooks
  /webhooks/{id}:
    delete:
      description: Deletes a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Webhook deleted successfully
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      summary: Delete a webhook
      tags:
      - Webhooks
    put:
      consumes:
      - application/json
      description: Updates the configuration of a webhook by its ID.
      parameters:
      - description: Webhook ID
        in: path
        name: id
        required: true
        type: string
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Webhook updated successfully
        "400":
          description: Invalid request payload
        "404":
          description: Webhook not found
        "500":
          description: Internal server error
      summary: Update a webhook
      tags:
      - Webhooks
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
